language: python

install:
  - pip install coveralls tox

script:
  - tox

after_success:
  - coveralls

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  - TOXENV=django18
  - TOXENV=django19
  - TOXENV=django110

matrix:
  exclude:
    - env: TOXENV=django19
      python: 3.3
    - env: TOXENV=django110
      python: 3.3
  fast_finish: true
